### ISSUE TITLE
New Major Release

### ISSUE THREAD

**Issue by eczy-tempus** [jianyuan/go-sentry#28]
Would it be possible to publish a new release? We are trying to take advantage of https://github.com/jianyuan/go-sentry/commit/1f63b220b97bdd5e6ae3e5e3855a8bf85ceecb13, but the last release was cut in October 2018. This release predates this commit, so we currently have to point to the current SHA in master which is non-ideal.

**Comment by jianyuan** [comment]
[v1.3.0](https://github.com/jianyuan/go-sentry/releases/tag/v1.3.0) was recently released 🎉

**Comment by eczy-tempus** [comment]
Thank you!
