### ISSUE TITLE
Metric alert has two types of response

### ISSUE THREAD

**Issue by eugeniykurasov** [jianyuan/go-sentry#72]
When we create project alerts with integrations (for example slack) we are expected response like `MetricAlert`
(https://github.com/jianyuan/go-sentry/blob/8f147c7d7e2fda2420a41cb5543776493c1d7cda/sentry/metric_alerts.go#L11)

Here is method: https://github.com/jianyuan/go-sentry/blob/8f147c7d7e2fda2420a41cb5543776493c1d7cda/sentry/metric_alerts.go#L111

Here is endpoint from sentry repository.
https://github.com/getsentry/sentry/blob/41f9103679d2669ab5e9b32a8e2b1970578e4f4e/src/sentry/incidents/endpoints/project_alert_rule_index.py#L112

**Comment by eugeniykurasov** [comment]
Uuid is using in next endpoint `https://sentry.io/api/0/projects/<organizationName>/<alertsName>/alert-rule-task/<uuid>/`:

https://github.com/getsentry/sentry/blob/41f9103679d2669ab5e9b32a8e2b1970578e4f4e/src/sentry/incidents/endpoints/project_alert_rule_task_details.py#L16

**Comment by eugeniykurasov** [comment]
@jianyuan Do you have idea how better that should be implemented? My proposition I can implement in method additional calls inside of method create metric.

**Comment by jianyuan** [comment]
I would return nil as the `*MetricAlert` and an error that the user can then inspect. e.g.

```go
type MetricAlertAsyncError struct {
    UUID string
}

func (e MetricAlertAsyncError) Error() {
    return fmt.Sprintf("response will be available later: %v", e.UUID)
}
```

```
metricAlert, respErr, err := client.MetricAlerts.Update(ctx, "org-slug", "project-slug", "alert-rule-id", &MetricAlert{...})
if err != nil {
  if err, ok := err.(MetricAlertAsyncError); ok {
    fmt.Println("UUID was %v", err.UUID)
  }
}
```

**Comment by eugeniykurasov** [comment]
But there is not error, http status is 202 (The request has been accepted for processing, but the processing has not been completed). 

So it's should be response like:

```
type MetricAlertAsync struct {
    UUID string
}
```
But how and where it will handle?

**Comment by jianyuan** [comment]
@eugeniykurasov It seems that we've done something similar to what you've described in the [issues alert method](https://github.com/jianyuan/go-sentry/blob/8f147c7d7e2fda2420a41cb5543776493c1d7cda/sentry/issue_alerts.go#L109-L115).

In hindsight, I prefer for the user to handle the retries instead of the library. I think returning an error is a good way to tell the user to retry.

**Comment by eugeniykurasov** [comment]
Yes, I mean like [issues alert method](https://github.com/jianyuan/go-sentry/blob/8f147c7d7e2fda2420a41cb5543776493c1d7cda/sentry/issue_alerts.go#L109-L115).

What sense retries calls instead of the library? So  method will be return 2 of success responses. I think that should be hide it. On client side you shouldn't care about additional calls. Action is create "alert" but instead you can get UUID, and than you need call other endpoint with logic of retry. So retries calls **going to repeat on each client sides** who use the lib.
