### ISSUE TITLE
Fix field autoAssignment in ProjectOwnership API

### ISSUE THREAD

**Issue by bigdatasourav** [jianyuan/go-sentry#79]
The ProjectOwnership API is returning an error -
https://pkg.go.dev/github.com/jianyuan/go-sentry/v2@v2.4.0/sentry#ProjectOwnershipsService.Get
`Error: json: cannot unmarshal string into Go struct field ProjectOwnership.autoAssignment of type bool`

**Comment by jianyuan** [comment]
Fixed in https://github.com/jianyuan/go-sentry/commit/a0eb7e65644508e312030ad5e52c8d925cf13300
