### ISSUE TITLE
Json Unmarshal Error

### ISSUE THREAD

**Issue by graza-io** [jianyuan/go-sentry#84]
Metric alert trigger actions can have a `string` or `int` value see [here](https://github.com/getsentry/sentry/blob/22.5.0/src/sentry/api/serializers/models/alert_rule_trigger_action.py#L24-L54) most specifically L#29 where it returns `int(action.target_identifier)`

This can result in the below error:
```sh
Error: json: cannot unmarshal number into Go struct field MetricAlertTriggerAction.triggers.actions.targetIdentifier of type string
```

https://github.com/jianyuan/go-sentry/blob/main/sentry/metric_alerts.go#L58

**Comment by jwoo0122** [comment]
Related: https://github.com/jianyuan/terraform-provider-sentry/issues/185#issuecomment-1811812420

**Comment by jwoo0122** [comment]
@jianyuan Would you check this? There's a trouble using sentry terraform with pagerduty because of this.

**Comment by jianyuan** [comment]
Fixed in https://github.com/jianyuan/go-sentry/commit/1199162bddecbb8d792d6bbfb9b7136e3918fc65
